/*
 * File:        solveEikonalEquation3d.c
 * Copyright:   (c) 2005-2006 Kevin T. Chu
 * Revision:    $Revision: 1.4 $
 * Modified:    $Date: 2006/09/18 16:17:02 $
 * Description: MATLAB MEX-file for using the fast marching method to
 *              compute the distance function for 3d level set functions
 */

/*=================================================================
 *
 * solveEikonalEquation3d() solves the Eikonal equation
 *
 *   |grad(phi)| = 1/speed(x,y,z)
 *
 * in two-dimensions using the Fast Marching Method.
 *
 * Usage: phi = solveEikonalEquation3d(boundary_data, speed, dX, ...
 *                                     mask, spatial_derivative_order)
 *
 * Arguments:
 * - boundary_data:             data array containing boundary data and
 *                                domain information.  The value at grid
 *                                points adjacent to the boundary of the
 *                                domain should be set to the desired
 *                                positive values; the value at all other
 *                                grid points should be negative.
 * - speed:                     speed function in Eikonal equation
 * - dX:                        array containing the grid spacing
 *                                in each coordinate direction
 * - mask:                      mask for domain of problem;
 *                                grid points outside of the domain
 *                                of the problem should be set to a
 *                                negative value
 *                                (default = [])
 * - spatial_derivative_order:  order of discretization for 
 *                                spatial derivatives
 *                                (default = 5)
 *
 * Return value:
 * - phi:                       solution to Eikonal equation
 *
 * NOTES:
 * - It is the user's responsibility to set the boundary_data for phi. 
 *   Grid points where the value of phi are to be solved for MUST be 
 *   set to a negative value. 
 *
 * - All data arrays are assumed to be in the order generated by the
 *   MATLAB meshgrid() function.  That is, data corresponding to the
 *   point (x_i,y_j,z_k) is stored at index (j,i,k).
 *
 * - It is NOT necessary to mask out regions where the speed is zero.
 *   Grid points where the speed is zero are automatically treated as
 *   being outside of the domain.
 * 
 * - boundary_data, speed, and mask MUST have the same grid dimensions.
 *
 *===========================================================================*/

#include "mex.h"
#include "lsm_fast_marching_method.h" 

/* Input Arguments */
#define BOUNDARY_DATA	           (prhs[0])
#define SPEED	                   (prhs[1])
#define DX                         (prhs[2])
#define MASK                       (prhs[3])
#define SPATIAL_DERIVATIVE_ORDER   (prhs[4])

/* Output Arguments */
#define PHI                        (plhs[0])


void mexFunction(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
{
  /* field data */
  double *boundary_data;
  double *phi;
  double *speed;
  double *mask;
 
  /* grid data */
  const int *grid_dims_phi = mxGetDimensions(BOUNDARY_DATA);
  const int *grid_dims_speed = mxGetDimensions(SPEED);
  int num_gridpts; 
  double *dX = mxGetPr(DX);
  double dX_matlab_order[3]; 

  /* numerical parameters */
  int spatial_derivative_order;

  /* auxilliary variables */
  int i;
  int error_code;
  mxArray* tmp_mxArray;

  /* Check for proper number of arguments */
  if (nrhs < 3) {
    mexErrMsgTxt(
      "Insufficient number of input arguments (3 required; 2 optional)");
  } else if (nrhs > 5) {
    mexErrMsgTxt("Too many input arguments (3 required; 2 optional)");
  } else if (nlhs > 1) {
    mexErrMsgTxt("Too many output arguments.");
  }

  /* Check for that grid dimensions are the same */
  if ( (grid_dims_phi[0] != grid_dims_speed[0]) ||
       (grid_dims_phi[1] != grid_dims_speed[1]) ||
       (grid_dims_phi[1] != grid_dims_speed[2]) ) {
    mexErrMsgTxt("The dimensions for phi and speed should be the same.");
  }

  /* Get mask */
  if (nrhs < 4) {
    mask = 0;  /* NULL mask ==> all points are in interior of domain */
  } else {
    mask = mxGetPr(MASK);
  }

  /* Get spatial derivative order */
  if (nrhs < 5) {
    spatial_derivative_order = 1;  /* KTC - change this to 2 after */
                                   /* implementing second-order algorithm */
  } else {
    spatial_derivative_order = mxGetPr(SPATIAL_DERIVATIVE_ORDER)[0];
  }
  
  /* Assign pointers for boundary_data and speed data */
  boundary_data = mxGetPr(BOUNDARY_DATA);
  speed = mxGetPr(SPEED);

  /* Create and initialize PHI data */
  PHI = mxCreateNumericArray(3, grid_dims_phi, mxDOUBLE_CLASS, mxREAL);
  phi = mxGetPr(PHI);
  num_gridpts = grid_dims_phi[0]*grid_dims_phi[1]*grid_dims_phi[2];
  for (i = 0; i < num_gridpts; i++) {
    phi[i] = boundary_data[i];
  }

  /* Change order of dX to be consistent with MATLAB order for grids. */
  dX_matlab_order[0] = dX[1];
  dX_matlab_order[1] = dX[0];
  dX_matlab_order[2] = dX[2];

  /* Carry out FMM calculation */
  error_code = solveEikonalEquation3d(
                 phi,
                 speed,
                 mask,
                 spatial_derivative_order,
                 (int*) grid_dims_phi,
                 dX);

  if (error_code) {
    mexErrMsgTxt("solveEikonalEquation3d failed...");
  }

  return;
}
